on:
  workflow_dispatch: {}
  # pull_request_review
  # types      submitted: []
  pull_request: {}
  push:
    branches:
      - main
      - master
  schedule:
    - cron: 25 17 * * *
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-20.04
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: returntocorp/semgrep
    steps:
      - uses: actions/checkout@v3
      - run: semgrep ci
